language: node_js

node_js:
  - '10'

branches:
  only:
    - master

before_install:
  - npm install -g @angular/cli

install: npm install

script:
  - npm run lint

deploy:
  provider: heroku
  api_key:
    secure: 2j/563PWhF5IxyHuN1ILfugL68eYk1emAe3uOVt9/Q6qc4jR+g5dKK08N1tXc8fogUtzj/DIfV1u1oQ0mkC9Xbob8dtcjzW2c5BvaPiC5VedtMMFFMT3oyGM+Tq7WdTiYEskBvaa8h9DjFO2KkDLOdClfZkYg4Qqo0Pm5/MhGGNb8cCTOIcI68BPmTYUMk/nKusFclSICAXokBmX2vuzrkaWHikq4/8PDCVSm7RqbbqOZcnt0FICt/BylUNdE2W3iX/IRX+mBXqw8Wj+oKYYWLPIxy0J0b46JXU9H+1/4/lvay9yQ7E2yDiJh93GtCTYD+Anfw0kqXSMaQcK4jhb0f83UC98Zs4uGyDGX9o/Aqn0/lHbvAyY8xPHXPeNW5OsawKEgnS54d6zqq0Kf41Naqz8Ju9k1v7NZ8BKAjJVPb45o2Iaqi3oUAkR3v71XXeeBoJqym2YaanKVBz2ncqVckxmor1yEWIUnaisOTDGApoGj5anYKMb/sEgm1vg7zlOO34FxBvSTTxHtSjGUMEWIbklYLyAyrDhz7FysRp+nvSEskwKGLdOMGtR/B79hYtTzS8R2F5tF2K9W2EKCEI5dgoyRarwEMm4JdeKLZZ8/sLbhRgtNtKYDWASFYAzGEqRxzkpj2stxUvkt/PWOuuXYhLX7NQ7onbf+RfPLeOYQS0=
  app: quotes-frontend
  on:
    repo: meetup-demo/quotes-frontend
